---
# yamllint disable rule:line-length

language: python

python:
  # Should match the versions listed in ./setup.py
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -e '.[test]'"
  - "pip install -r docs/requirements.txt"

script:
  - "make NOSETESTS=nosetests check"
