#!/bin/bash
# Analyse pcap files.

file="$1"
dir="$file.analysis"
if [[ ! -r "$file" ]]; then
    echo "Give pcap file."
    exit 1
fi

date
mkdir -p "$dir"

[[ -e "$dir/ettercap.txt" ]] || ettercap -Tq -r "$file" |grep -v '^DHCP' > "$dir/ettercap.txt"
cat "$dir/ettercap.txt"

[[ -e "$dir/chaosreader" ]] || chaosreader --application --raw --preferdns --info --quiet --names --dir "$dir/chaosreader/" "$file"
