#!/bin/bash
# @author sdrfnord
# @license GPLv3+
# Generate random but valid mac address for certain vendors.

wireshark_manuf_file="/usr/share/wireshark/manuf"

if [ ! -r "$wireshark_manuf_file" ]; then
    wireshark_manuf_file="`locate --regexp 'wireshark/manuf$' --limit 1`"
    if [ ! -r "$wireshark_manuf_file" ]; then
        echo "manuf file not found." 1>&2
        exit 1
    fi
fi

rand_mac_line=`grep -v '^#' "$wireshark_manuf_file"| \
    grep -P ' (Intl|Hwlett-|Fujitsu) ' \
    | shuf -n 1`

echo "Manufacture which uses this MAC address: ${rand_mac_line}."
rand_mac_manf_part=${rand_mac_line:0:8}
rand_mac_random_part="`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`"
rand_mac="${rand_mac_manf_part}:${rand_mac_random_part}"
echo "Random MAC: $rand_mac"
