#!/bin/bash
# Script to easily set your wireless card in monitor mode and show the IEEE 802.11 frames that are flowing around you.

# Always exit on errors
set -e
# Undefined variables, we don't like you
# set -u
# ERR traps are inherited by shell functions, command substitutions and
# commands executed in a subshell environment.
set -E

if [[ "$1" == "start" ]]; then
    service network-manager stop
    # Unblock all wireless cards {{{
    for count in `seq 2`; do
        rfkill list |grep Wireless|while read rfkill_line;do
            rfkill unblock ${rfkill_line:0:1}
        done
    done
    rfkill list
    # }}}
    if [[ -z "`airmon-ng |grep mon0`" ]]; then
        airmon-ng start wlan0
    fi
    airodump-ng --manufacturer --uptime mon0
    if [[ $? != 0 ]]; then
        airodump-ng --uptime mon0
    fi
elif [[ "$1" == "stop" ]]; then
    killall 'airodump-ng' || true
    airmon-ng stop mon0
    airmon-ng stop wlan0
    service network-manager start
else
    echo 'Please call script with "start" or "stop".'
fi
